<?php

declare(strict_types=1);

namespace SpitsOnline\Openprovider\Enums;

/**
 * The DNS record types Openprovider hosts. SOA records are generated by
 * Openprovider and can't be added, changed or removed.
 */
enum RecordType: string
{
    case A = 'A';
    case AAAA = 'AAAA';
    case CAA = 'CAA';
    case CNAME = 'CNAME';
    case MX = 'MX';
    case NS = 'NS';
    case SOA = 'SOA';
    case SPF = 'SPF';
    case SRV = 'SRV';
    case SSHFP = 'SSHFP';
    case TLSA = 'TLSA';
    case TXT = 'TXT';

    public function isEditable(): bool
    {
        return $this !== self::SOA;
    }
}
