<?php

declare(strict_types=1);

namespace SpitsOnline\Openprovider\Enums;

/**
 * The DNS record types Openprovider hosts. SOA records are generated by
 * Openprovider and can't be added, changed or removed.
 */
enum RecordType: string
{
    case A = 'A';
    case Aaaa = 'AAAA';
    case Caa = 'CAA';
    case Cname = 'CNAME';
    case Mx = 'MX';
    case Ns = 'NS';
    case Soa = 'SOA';
    case Spf = 'SPF';
    case Srv = 'SRV';
    case Sshfp = 'SSHFP';
    case Tlsa = 'TLSA';
    case Txt = 'TXT';

    public function isEditable(): bool
    {
        return $this !== self::Soa;
    }
}
