<?php

declare(strict_types=1);

namespace SpitsOnline\Openprovider\Exceptions;

use SpitsOnline\Openprovider\Enums\RecordType;

final class InvalidRecord extends OpenproviderException
{
    public static function readOnly(RecordType $type): self
    {
        return new self("{$type->value} records are generated by Openprovider and can't be added, changed or deleted.");
    }
}
