<?php

declare(strict_types=1);

use Carbon\CarbonImmutable;
use SpitsOnline\Openprovider\Data\Domain;
use SpitsOnline\Openprovider\Data\DomainName;
use SpitsOnline\Openprovider\Data\Record;
use SpitsOnline\Openprovider\Data\Zone;
use SpitsOnline\Openprovider\Enums\RecordType;
use SpitsOnline\Openprovider\Enums\Ttl;
use SpitsOnline\Openprovider\Exceptions\InvalidDomainName;
use SpitsOnline\Openprovider\Exceptions\InvalidRecord;
use SpitsOnline\Openprovider\Openprovider;

it('builds a record with Openprovider\'s smallest TTL and no name by default', function () {
    expect(Record::create(RecordType::A, '1.2.3.4')->toArray())
        ->toBe(['type' => 'A', 'value' => '1.2.3.4', 'ttl' => 900]);
});

it('sends the name, TTL and priority it was given', function () {
    expect(Record::create(RecordType::MX, 'mail.example.com', 'mail', Ttl::DAY, 20)->toArray())
        ->toBe(['name' => 'mail', 'type' => 'MX', 'value' => 'mail.example.com', 'ttl' => 86400, 'prio' => 20]);
});

it('gives an MX record a priority when you leave it out, and no other type', function () {
    expect(Record::create(RecordType::MX, 'mail.example.com')->priority)->toBe(Record::DEFAULT_MX_PRIORITY)
        ->and(Record::create(RecordType::A, '1.2.3.4')->priority)->toBeNull();
});

it('refuses to build an SOA record, which Openprovider generates', function () {
    expect(fn () => Record::create(RecordType::SOA, 'ns1 dns 1 2 3 4 5'))
        ->toThrow(InvalidRecord::class, "SOA records are generated by Openprovider and can't be added, changed or deleted.");
});

it('reads a record as Openprovider sends it', function () {
    $record = Record::fromArray(['name' => 'www.example.com', 'type' => 'CNAME', 'value' => 'example.com', 'ttl' => '3600', 'ip' => '127.0.0.1']);

    expect($record)
        ->type->toBe(RecordType::CNAME)
        ->ttl->toBe(3600)
        ->priority->toBeNull()
        ->raw->toHaveKey('ip', '127.0.0.1');
});

it('refuses to read an SOA record as a record you can change', function () {
    expect(fn () => Record::fromArray(['type' => 'SOA', 'value' => 'ns1 dns 1 2 3 4 5', 'ttl' => 3600]))
        ->toThrow(InvalidRecord::class, "SOA records are generated by Openprovider and can't be added, changed or deleted.");
});

it('compares records by what they describe, not by their payload', function () {
    $read = Record::fromArray(['name' => 'www', 'type' => 'A', 'value' => '1.2.3.4', 'ttl' => 900, 'creation_date' => '']);

    expect($read->is(Record::create(RecordType::A, '1.2.3.4', 'www')))->toBeTrue()
        ->and($read->is(Record::create(RecordType::A, '1.2.3.4', 'www', Ttl::HOUR)))->toBeFalse();
});

it('only treats SOA records as not editable', function () {
    expect(array_filter(RecordType::cases(), fn (RecordType $type) => ! $type->isEditable()))
        ->toBe([6 => RecordType::SOA]);
});

it('splits a domain at its first dot', function (string $domain, string $name, string $extension) {
    expect(DomainName::parse($domain))
        ->name->toBe($name)
        ->extension->toBe($extension)
        ->and((string) DomainName::parse($domain))->toBe($domain);
})->with([
    ['example.com', 'example', 'com'],
    ['example.co.uk', 'example', 'co.uk'],
]);

it('passes a parsed domain name through', function () {
    $name = new DomainName('example', 'com');

    expect(DomainName::parse($name))->toBe($name);
});

it('rejects text that is not a domain', function (string $domain) {
    expect(fn () => DomainName::parse($domain))->toThrow(InvalidDomainName::class);
})->with(['localhost', '.com', 'example.', '']);

it('reads dates as immutable Carbon instances in the app timezone', function () {
    config()->set('app.timezone', 'UTC');
    date_default_timezone_set('UTC');

    $zone = Zone::fromArray(['id' => 1, 'name' => 'example.com', 'creation_date' => '2019-06-27 06:22:36', 'modification_date' => ''], app(Openprovider::class));

    expect($zone->createdAt)->toBeInstanceOf(CarbonImmutable::class)
        ->and($zone->createdAt->toIso8601String())->toBe('2019-06-27T06:22:36+00:00')
        ->and($zone->modifiedAt)->toBeNull();
});

it('reads dates in openprovider.timezone when it is set', function () {
    config()->set('openprovider.timezone', 'Europe/Amsterdam');

    $domain = Domain::fromArray(['id' => 1, 'domain' => ['name' => 'example', 'extension' => 'com'], 'expiration_date' => '2022-09-27 07:03:04'], app(Openprovider::class));

    expect($domain->expirationDate->toIso8601String())->toBe('2022-09-27T07:03:04+02:00')
        ->and($domain->renewalDate)->toBeNull();
});

it('writes dates back in Openprovider\'s format', function () {
    config()->set('openprovider.timezone', 'Europe/Amsterdam');

    $zone = Zone::fromArray(['id' => 1, 'name' => 'example.com', 'creation_date' => '2019-06-27 06:22:36'], app(Openprovider::class));

    expect($zone->toArray())->toMatchArray(['creation_date' => '2019-06-27 06:22:36', 'modification_date' => null]);
});

it('quotes a TXT value the way Openprovider stores it, once', function (string $value, string $stored) {
    expect(Record::create(RecordType::TXT, $value)->stored()->value)->toBe($stored);
})->with([
    'plain' => ['v=spf1 -all', '"v=spf1 -all"'],
    'already quoted' => ['"v=spf1 -all"', '"v=spf1 -all"'],
    'split into strings' => ['"part one" "part two"', '"part one" "part two"'],
    'a lone quote' => ['"', '"""'],
]);

it('leaves other record types as they are', function () {
    $record = Record::create(RecordType::A, '1.2.3.4');

    expect($record->stored())->toBe($record);
});

it('treats a TXT record and its quoted copy as the same record', function () {
    expect(Record::create(RecordType::TXT, 'x')->is(Record::create(RecordType::TXT, '"x"')))->toBeTrue()
        ->and(Record::create(RecordType::TXT, 'x')->is(Record::create(RecordType::TXT, 'y')))->toBeFalse();
});
